### ISSUE TITLE
(enh) add client details to log

### ISSUE THREAD

**Issue by asafMasa** [MapColonies/image-exporter-client#125]
- [ ] browser
- [ ] os
- [ ] device
- [ ] userAgent
- [ ] os_version

- [ ] isMobile : returns if the device is a mobile device (android / iPhone/ windows-phone etc) OR
       isTablet() : returns if the device us a tablet (iPad etc) OR
       isDesktop() : returns if the app is running on a Desktop browser.

try to use something like https://www.npmjs.com/package/ngx-device-detector

**Comment by alebinson** [comment]
The send object will be in following formt:
```
{
 browser: "Chrome"
 browser_version: "88.0.4324.104"
 device: "browser"
 mobile_model: "none"
 mobile_vendor: "none"
 os: "Windows"
 os_version: "10"
 user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, lik.....)
}
```
