### ISSUE TITLE
Send BBOX Request to BL

### ISSUE THREAD

**Issue by asafMasa** [MapColonies/image-exporter-client#20]
- The user needs to confirm the request
- The user will get send successfully/failed notification (toast?)
- Post message will be send to url (configuration) with the following params
{
   layers: "[{layerType: "raster", layerUrl: rasterLayerUrl}]", -> currently only one value (rasterLayer) in the array (from config)
   bbox: [bottomLeft, topRight],
   folder and package data as specified in https://github.com/MapColonies/image-exporter-client/issues/4
}

**Comment by alebinson** [comment]
@asafMasa @ssharon-rnd  Regarding "folder selection" from spec #4 

_Folder selection section.
3.1. An option to select a mapped shared folder or local folder --> **what is local folder?**
3.1.1. If shared folder was selected display copy to clipboard the folder location
3.2. Create folder on the shared folder/ or local folder --> **is it in scope?**
3.3 Package name text box.
3.4 Progress bar --> **is it in scope? probably not at that stage?**
_
