### ISSUE TITLE
use confd

### ISSUE THREAD

**Issue by asafMasa** [MapColonies/image-exporter-client#38]
we need the ability to get the config from outside into the docker - as we use in other projects with confd, try to adapt it to your code

**Comment by alebinson** [comment]
@asafMasa please review following [config file](https://github.com/MapColonies/image-exporter-client/blob/master/src/common/config/index.ts)  what we suppose to receive from outside?
My proposition is:
```
const MAP_SERVER = 'http://10.28.11.125';
const PUBLISH_POINT = 'blue_m_flat2d-v001';
const CHANNEL = 1002;
const VERSION = 1;
const REQUEST = 'ImageryMaps';

const EXPORTER_CONFIG = {
  SERVICE_PROTOCOL: 'http://',
  SERVICE_NAME: 'localhost:8000',
  ...
}
```
