### ISSUE TITLE
fix(size estimation): size estimation isn't close enough to real size

### ISSUE THREAD

**Issue by shimoncohen** [MapColonies/image-exporter-client#60]

**Comment by alebinson** [comment]
When you open bugs supply as much details as you can.
Sreenshots do the job

**Comment by ssharon-rnd** [comment]
@shimoncohen Can you explain this?

**Comment by shimoncohen** [comment]
@ssharon-rnd 
The geopackage generated is always larger than the estimation shown in the UI (at least double the estimation).

**Comment by alebinson** [comment]
@shimoncohen GOOD one, I always ask to see the correlation. 
Do you know with what max zoom it's really exported? Number of real tiles exported?
The ESTIMATED package size depends on MAX_ZOOM --> ESTIMATED_TILES-COUNT * AVG_TILE_SIZE_MB (0.02)
Do you know REAL numbers?

**Comment by CL-SHLOMIKONCHA** [comment]
@alebinson we can't really tell the amount of tiles that gdal is exports right now, gdal gives us only the progress while in proccess

**Comment by shimoncohen** [comment]
May be of some use: [OSM tile calculator](https://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=34.614068,31.056742,35.248773,31.594857)

**Comment by asafMasa** [comment]
* remove from UI the Min-Max Zoom as we can't control it on the gdal process
* set the zoom level of the calculated tile size to 21 or 23
* remove the link url line as it's not the real link path (we will know it only when the file is created)
