### ISSUE TITLE
fix: when choosing an small poligon with est 0 tiles & 0 mb the client freezes and crashes 

### ISSUE THREAD

**Issue by CL-SHLOMIKONCHA** [MapColonies/image-exporter-client#62]
I have tried to export and GPKG , while i'm zoom in and choosing an small area of poligon and then click 'export' i get estimate 0TILES and 0MB and the client immediately freezes and crushes after a while.

**Comment by alebinson** [comment]
@asafMasa @CL-SHLOMIKONCHA 
Think we MUST include following info when opening the bug:
1. Where? - Environment
2. What? - Screenshots, logs, any other data that can help
3. Expectation? - Real

**Comment by alebinson** [comment]
@shimoncohen @CL-SHLOMIKONCHA tried to reproduce it with this BBox
![image](https://user-images.githubusercontent.com/23166717/96827455-4d291d00-143e-11eb-8aad-9691892a17de.png)
Works as expected. 
Are you sure it was tested on latest master?

**Comment by CL-SHLOMIKONCHA** [comment]
@alebinson  , I tried it before i opened this bug with roee, we both got our devices stuck and crashed on diff devices yesterday with the same way u just did on the screenshot.. 
roee just published the latest master on the vm yesterday then yes, we checked it on latest.

**Comment by CL-SHLOMIKONCHA** [comment]
I've tried this again just now, i zoomed in and chose small area of an box to export. 
seems like the client is freezes again BUT after a while (20-30sec) it shows the est tile and est size
![Screenshot from 2020-10-22 09-39-43](https://user-images.githubusercontent.com/65117898/96836035-14dd0b00-144d-11eb-8c5e-ea8eb8ed2fb2.png)

**Comment by CL-SHLOMIKONCHA** [comment]
> I've tried this again just now, i zoomed in and chose small area of an box to export.
> seems like the client is freezes again BUT after a while (20-30sec) it shows the est tile and est size
> ![Screenshot from 2020-10-22 09-39-43](https://user-images.githubusercontent.com/65117898/96836035-14dd0b00-144d-11eb-8c5e-ea8eb8ed2fb2.png)

maybe its not yet finish to calculate the est tile and size and whats happens.

**Comment by alebinson** [comment]
Do you have Chrome?

**Comment by CL-SHLOMIKONCHA** [comment]
I'm on FireFox

**Comment by alebinson** [comment]
The failure is consistent for this Bbox:
TopRight [Lat,Lon]
[31.97818342861753,   34.7381191565087]

BottomLeft[Lat,Lon]
[31.97818342861753,   34.73811915565087]
